### ISSUE TITLE
Packaging ?

### ISSUE THREAD

**Issue by gl-yziquel** [stephen-huan/inflow#1]
Hi.

I've been struggling with getting to understand par and thought I'd try inflow.

Would be lovely if it could be installed with a `python -m build --wheel` invocation.

**Comment by stephen-huan** [comment]
I've added a pyproject.toml in d7a9b212029a0c0fe31f25f3e5b54d0b6911ef2b and published inflow to PyPi as [python-inflow](https://pypi.org/project/python-inflow/). This means you should be able to `pip install python-inflow` and have `inflow` on your `$PATH`. Let me know if this is not the case.

I am new to Python packaging so please also let me know if you notice anything wrong. Thanks!

**Comment by stephen-huan** [comment]
For completeness, I should mention that the C++ implementation of inflow is packaged in [Nixpkgs](https://github.com/nixos/nixpkgs) as [pkgs.inflow](https://search.nixos.org/packages?channel=unstable&query=inflow).

The only dependency is the C++ standard library (std). [inflow.cpp](https://github.com/stephen-huan/inflow/blob/master/inflow.cpp) can be compiled with

```console
g++ -Wall -Wpedantic -Wextra -O3 -o inflow inflow.cpp
```

or with clang,

```console
clang++ -Wall -Wpedantic -Wextra -O3 -o inflow inflow.cpp
```

**Comment by gl-yziquel** [comment]
I, unfortunately, do not use nix yet, for a variety of reasons.

The python package does build. I guess I'll take some time to come back to you, as I have to check where in my setup would far / inflow replace par usage.

Hope to come back to you. Thank you for having made the packaging effort. That packaging seems to do the job.
